// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:freeaihub/core/models/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AiCharacterModelAdapter());
    registerAdapter(AiCharacterParametersModelAdapter());
    registerAdapter(AuthorTypeAdapter());
    registerAdapter(ChatSessionAdapter());
    registerAdapter(ImageDataAdapter());
    registerAdapter(ImageDimensionsAdapter());
    registerAdapter(MediaItemAdapter());
    registerAdapter(MediaSourceAdapter());
    registerAdapter(MediaTypeAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(MessageAuthorAdapter());
    registerAdapter(MessageTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AiCharacterModelAdapter());
    registerAdapter(AiCharacterParametersModelAdapter());
    registerAdapter(AuthorTypeAdapter());
    registerAdapter(ChatSessionAdapter());
    registerAdapter(ImageDataAdapter());
    registerAdapter(ImageDimensionsAdapter());
    registerAdapter(MediaItemAdapter());
    registerAdapter(MediaSourceAdapter());
    registerAdapter(MediaTypeAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(MessageAuthorAdapter());
    registerAdapter(MessageTypeAdapter());
  }
}
